pipelines:
  - name: zen-npm-demo
    steps:
      - name: bld_frontend
        type: NpmBuild
        configuration:
            npmArgs: --no-progress --no-audit
            sourceLocation: /
            repositoryName: npm
            inputResources:
              - name: GitHub
            integrations:
              - name: artifactory
      