pipelines:
  - name: zen-npm-demo
    steps:
      - name: zen_frontend
        type: NpmBuild
        configuration:
            npmArgs: --no-progress --no-audit
            sourceLocation: /
            repositoryName: npm
            inputResources:
              - name: wm_GitRepo
            integrations:
              - name: ArtifactoryHA
      