pipelines:
  - name: zen_npm_demo_pipelines
    steps:
      - name: NpmBuild
        type: NpmBuild
        configuration:
          npmArgs: --no-progress --no-audit
          sourceLocation: /
          repositoryName: npm
          inputResources:
            - name: wmanning_gitRepo
          integrations:
            - name: ArtifactoryUnified
      - name: NpmBuildPublish
        type: NpmPublish
        configuration:
          repositoryName: npm
          autoPublishBuildInfo: true
          forceXrayScan: false 
          inputSteps:
            - name: NpmBuild
          integrations:
            - name: ArtifactoryUnified
          outputResources:
            - name: NpmBuildInfo
        execution:
          onStart:
            - export inputNpmBuildStepName="zen_frontend"
      - name: promoteNpmBuildQA
        type: PromoteBuild
        configuration:
          targetRepository: npm-release-local
          includeDependencies: true    
          status: "Released" 
          comment: "This is Zen Front End is ready for release"
          copy: true
          integrations:
            - name: ArtifactoryUnified
          inputResources:
            - name: NpmBuildInfo
          outputResources:
            - name: NpmBuildInfoPromotedQA
      - name: promoteNpmBuildProd
        type: PromoteBuild
        configuration:
          targetRepository: npm-release-local
          includeDependencies: true    
          status: "QA - Tested" 
          comment: "This build has passed all QA testing"
          copy: true
          integrations:
            - name: ArtifactoryUnified
          inputResources:
            - name: NpmBuildInfoPromotedQA
          outputResources:
            - name: promoteNpmBuildProd
      - name: NPMZenBundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: NPMZenBundle
          releaseBundleVersion: v1.0.$run_number
          dryRun: false
          sign: true
          description: "Zen NPM Release Bundle"
          inputResources:
            - name: promoteNpmBuildProd
          outputResources:
            - name: NPMZenBundle

      