pipelines:
  - name: zen_npm_demo
    steps:
      - name: zen_frontend
        type: NpmBuild
        configuration:
          npmArgs: --no-progress --no-audit
          sourceLocation: /
          repositoryName: npm
          inputResources:
            - name: wmanning_gitRepo
          integrations:
            - name: ArtifactoryUnified
      - name: zen_npm_demo_publish_frontend_demo
        type: NpmPublish
        configuration:
          repositoryName: npm-dev-local
          inputSteps:
            - name: zen_frontend
          integrations:
            - name: ArtifactoryUnified
        execution:
          onStart:
            - export inputNpmBuildStepName="zen_frontend"
      - name: zen_npm_demo_publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: zen_npm_demo_publish_frontend_demo
          integrations:
            - name: ArtifactoryHA
          outputResources:
            - name: NpmBuildInfo
      